version: '3'
services:
    nginx:
        image: nginx:alpine
        network_mode: bridge
        environment:
            - VIRTUAL_HOST=${PROJECT_URL}
        volumes:
            - .:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: marvinenf/php-dev
        network_mode: bridge
        volumes:
            - .:/var/www/html